#!/usr/bin/env python3
"""Embed the built-in `zelto/*` JS modules into a C lookup table.

The modules in script/js/ are ordinary JS files (editable, lintable, diffable);
this turns them into string literals so the runtime has no files to find at boot
— a .zap ships one binary and the app's own bundle, not a copy of the stdlib.

Usage: js2c.py OUT.c NAME=PATH.js [NAME=PATH.js ...]
where NAME is the module specifier scripts import (e.g. "zelto/ui").
"""
import sys


def c_bytes(text: str) -> str:
    """A NUL-terminated byte array.

    Not a string literal: ISO C only guarantees 4095 characters in one, and a
    module sails past that — so -Wpedantic (which this project builds with)
    rejects the obvious encoding.
    """
    data = text.encode("utf-8") + b"\0"
    lines = []
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        lines.append(f"    {chunk},")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        return 2

    out_path = sys.argv[1]
    modules = []
    for spec in sys.argv[2:]:
        name, _, path = spec.partition("=")
        with open(path, encoding="utf-8") as f:
            modules.append((name, f.read()))

    parts = [
        "// GENERATED by script/js2c.py — do not edit.",
        "// Source: script/js/*.js (edit those, then rebuild).",
        "",
        '#include <string.h>',
        '',
        '#include "internal.h"',
        "",
    ]
    for i, (name, source) in enumerate(modules):
        parts.append(f"// {name}")
        # unsigned char, because the sources are UTF-8: a byte above 0x7f does
        # not fit a (signed) char without an overflow diagnostic.
        parts.append(f"static const unsigned char zs_mod_{i}[] = {{")
        parts.append(c_bytes(source))
        parts.append("};")
        parts.append("")

    parts.append("static const struct { const char *name; const char *source; }")
    parts.append("zs_builtins[] = {")
    for i, (name, _) in enumerate(modules):
        parts.append(f'    {{"{name}", (const char *)zs_mod_{i}}},')
    parts.append("};")
    parts.append("")
    parts.append("const char *zs_builtin_module(const char *name) {")
    parts.append("    for (size_t i = 0; i < sizeof(zs_builtins) / sizeof(zs_builtins[0]); i++) {")
    parts.append("        if (strcmp(zs_builtins[i].name, name) == 0) {")
    parts.append("            return zs_builtins[i].source;")
    parts.append("        }")
    parts.append("    }")
    parts.append("    return NULL;")
    parts.append("}")
    parts.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
